int mainmenu();
int compression();
int decompression();
char *creatMasterarray(int);
char *getma(int);
int unique(char, char *);
unsigned char charindex(unsigned char ch, char *ma);
int codelen(int);
int compression2(int,char *);
int compression3(int,char *);
int compression4(int,char *);
int compression5(int,char *);
int compression6(int,char *);
int compression7(int,char *);
int decompression2(int,char *);
int decompression3(int,char *);
int decompression4(int,char *);
int decompression5(int,char *);
int decompression6(int,char *);
int decompression7(int,char *);
int findIndex(unsigned char , char *);
char findChar(int , char *);
